language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=true


before_script:
    - dotnet restore ./Dramarr.Services.Checker/Dramarr.Services.Checker.csproj 
    - dotnet restore ./Dramarr.Services.Downloader/Dramarr.Services.Downloader.csproj
    - dotnet restore ./Dramarr.Services.Enqueuer/Dramarr.Services.Enqueuer.csproj
    - dotnet restore ./Dramarr.Services.Scraper/Dramarr.Services.Scraper.csproj
    - dotnet restore ./Dramarr.Services.Metadata/Dramarr.Services.Metadata.csproj
  
script:
    - dotnet build ./Dramarr.Services.Checker/Dramarr.Services.Checker.csproj --configuration Release
    - dotnet build ./Dramarr.Services.Downloader/Dramarr.Services.Downloader.csproj --configuration Release
    - dotnet build ./Dramarr.Services.Enqueuer/Dramarr.Services.Enqueuer.csproj --configuration Release
    - dotnet build ./Dramarr.Services.Scraper/Dramarr.Services.Scraper.csproj --configuration Release
    - dotnet build ./Dramarr.Services.Metadata/Dramarr.Services.Metadata.csproj --configuration Release